### ISSUE TITLE
Basisstructuur toevoegen

### ISSUE THREAD

**Issue by MateyByrd** [MateyByrd/CheckJeStress#1]

**Comment by Omniscimus** [comment]
Nu aanwezige pagina's:
* Index
* Tests **(formulieren)**
 * A: Quick-test
 * B: test voor managers, bestuurders en directeuren
 * C: uitgebreide test
 * D: burn-outrisicoanalyse voor bedrijven, ondernemingen en organisaties
* Ambitie
* Wat doen we
* Wie zijn we
 * Medewerkers
* Voor wie
 * Particulier
 * Bedrijf
 * Burnout-risicoanalyse voor bedrijven
 * Financiële gevolgen voor bedrijven
 * Producten
 * Inhoud Preventieplan
* Links / Nieuws
* Vacatures **(formulier)**
* Steunpunten bij jou in de buurt **(kaartje / JS / ?)**
 * Provincies
* Contact **(formulier)**
* Colofon
* Admin pagina's **(CMS)**

**Comment by Omniscimus** [comment]
Heb wat mapjes aangemaakt. De index.php pagina in elke map is de pagina waar je op belandt als je bijv. naar checkjestress.nl/mapnaam/ gaat.
_Ambitie_, _Wat doen we_ en _Wie zijn we_ kunnen we denk ik het beste samenvoegen tot één deel van de website: 'info/'.
'doelgroep/' is het deel waarin _Voor wie_ komt. Daar kunnen we misschien ook _Links_ en _Steunpunten bij jou in de buurt_ zetten.
_Colofon_ en _Contact_ lijken me goed om in de footer te zetten.
_Contact_ kan ook wel bovenaan. _Vacatures_ komt daar dan ook.
