### ISSUE TITLE
Logo veranderen in een vectorbestand

### ISSUE THREAD

**Issue by Coolpower** [MateyByrd/CheckJeStress#10]
Aangezien ik me al eerder bezig heb gehouden met het logo en andere visuele bestanden, zal ik proberen om deze taak op me te nemen. Het maken van het vectorbestand heeft geen gevolgen voor het favicon.

**Comment by Coolpower** [comment]
Zodra iedereen akkoord is met het nieuwe logo, kan deze issue wat mij betreft gesloten worden. Als iemand niet akkoord is, zal ik hier verder naar kijken.

**Comment by Omniscimus** [comment]
([Hier is hij](https://github.com/MateyByrd/CheckJeStress/blob/master/src/resources/img/logo_vector.svg))
Nice!!! :open_mouth: :+1: :+1:

**Comment by Omniscimus** [comment]
Dit kan handig zijn voor compatibility
```javascript
if (!document.createElement('svg').getAttributeNS) {
  // SVG niet supported; gebruik een .png
}
```
