### ISSUE TITLE
Meter for test results

### ISSUE THREAD

**Issue by Coolpower** [MateyByrd/CheckJeStress#11]
Voor de testresultaten moet een meter gemaakt worden. Gezien de vorige taken die ik gedaan heb, neem ik deze taak graag op me.

**Comment by Coolpower** [comment]
Een mogelijkheid is het volgende open-source project:

https://github.com/MadeByMike/svg-dash-meter

Hierbij wordt gebruik gemaakt van vectorbestanden, iets waar we volgens mij allemaal blij van worden.

**Comment by Omniscimus** [comment]
Misschien is het handiger als we eerst de tests zelf maken (#5), dan weten we ook in wat voor vorm de resultaten precies zijn. Bijv. float / double / int / etc. Dan weten we de opmaak e.d. ook. Metertje is meer een detail, denk ik.
