### ISSUE TITLE
Teksten verbeteren

### ISSUE THREAD

**Issue by Omniscimus** [MateyByrd/CheckJeStress#13]
In de map content/ heb ik de teksten gezet die van de originele website komen. Hier staan heel wat fouten in. Hier moet dus even goed naar gekeken worden.
- Steunpunt Stress Burnout Nederland moet veranderd naar CheckJeStress
- Niet telkens op een nieuwe regel beginnen, maar mooie paragrafen maken
- Hier en daar dingen wat consequenter maken. De lezer wordt bijvoorbeeld afwisselend met 'u' en 'je' aangesproken, en het hoofdlettergebruik is niet consequent
- Taalfouten verbeteren
- Fancy maken
- Eventueel complete rewrites, de inhoud van de teksten slaat soms ook nergens op. Bijv. hij kondigt een samenvatting aan en schrijft vervolgens een hele verhandeling.
- Links verbeteren / verwijderen (sommige links bestaan niet meer). Soms verwijst hij naar een pagina waarna je dan weer ergens anders op moet klikken, dan kun je beter meteen naar de doelpagina linken.

**Comment by Omniscimus** [comment]
Om er goed uit te komen in search engines, is het het beste als elke pagina minstens 250 (liefst rond 450) woorden bevat. Misschien is het dus goed om sommige pagina's samen te voegen.

**Comment by thealias** [comment]
#13 added bug fix

**Comment by thealias** [comment]
#13 add spelling check

**Comment by Omniscimus** [comment]
Dit is nu af (m.u.v. de dingen die we niet kunnen doen omdat we niet genoeg informatie / instructies hebben, zoals het stukje over Steunpunt Stress Burn-out Nederland op de homepagina).
