### ISSUE TITLE
Opmaak

### ISSUE THREAD

**Issue by MateyByrd** [MateyByrd/CheckJeStress#2]
Maak een basisversie van de opmaak die gebruikt gaat worden

**Comment by MateyByrd** [comment]
De basis opmaak van de top-bar is nu in gebruik

**Comment by Omniscimus** [comment]
Tekst die op een normale pagina staat, zit nu half in de menubalk bovenaan. Zie src/tests/testa.php. Er moet padding bij of hij moet inline ofzo. Ik heb geprobeerd om een lege div met een bepaalde hoogte in te voegen, maar dan klopt de voorpagina (src/index.php) ook niet meer. Heb niet getest op mobiel.

**Comment by MateyByrd** [comment]
De basis opmaak voor de index pagina is redelijk, heb vooral gefocust op de mobiele versie. Ik zal me later bezig houden met de desktop versie.
