### ISSUE TITLE
Contact link niet zichtbaar

### ISSUE THREAD

**Issue by Omniscimus** [MateyByrd/CheckJeStress#20]
Bij een browser width van ongeveer 655 px is de link naar de contactpagina rechts in de menubalk niet zichtbaar.
Mozilla Firefox 47.0a2, niet getest op andere browsers

**Comment by Coolpower** [comment]
Het volgende valt waarschijnlijk ook onder dit issue:

Bij een kleine breedte van de pagina (telefoon) scrolt de pagina niet naar de juiste positie wanneer op in-page links wordt gedrukt, wat bijvoorbeeld het geval is in "doelgroep-bedrijf" en bij de clickable map in "steunpunten".

**Comment by MateyByrd** [comment]
Volgens mij is het nu goed

**Comment by Omniscimus** [comment]
Het scrollen werkt nu bij mij, de contact link kan ik echter nog steeds niet zien bij een breedte van ±655px. Als ik de browser nog iets kleiner maak (waar de Steunpunten link start), switcht hij naar de responsive mobile layout.
![Screenshot](https://cloud.githubusercontent.com/assets/11180733/14580221/19846ebe-03c7-11e6-86d0-6ffd8756f948.png)

**Comment by MateyByrd** [comment]
Should be fixed
