### ISSUE TITLE
Styling voor test results pagina's

### ISSUE THREAD

**Issue by Omniscimus** [MateyByrd/CheckJeStress#22]
Dit is waarschijnlijk simpelweg een kwestie van een standaard pagina template erin gooien, maar toch een issue zodat we het niet vergeten.
Als je een test gedaan hebt, krijg je een pagina met advies en het metertje. Fancyheid nodig. Dit zit in de `createResultsPage` functie van src/resources/includes/TestCreator.php.

**Comment by Coolpower** [comment]
Volgens mij hoeft hier helemaal niet zo heel veel aan gewerkt te worden. Het enige probleem is op dit moment issue #16 op deze pagina's.

**Comment by Omniscimus** [comment]
o ja laat maar :satisfied:
