### ISSUE TITLE
Verbeteren logo en maken favicon

### ISSUE THREAD

**Issue by Omniscimus** [MateyByrd/CheckJeStress#3]
* Transparant maken
* Witte randjes eraf halen
* Andere verbeteringen?
* favicon maken met het logo (icoontje in je menubalk), voor verschillende apparaten, dus verschillende resoluties. Er zijn websites die dit automatisch doen voor heel veel verschillende devices

**Comment by Coolpower** [comment]
Ik ga hier nu aan werken

**Comment by Omniscimus** [comment]
:+1: Je kunt ook jezelf assignen, zie 'Assignee' rechts. Ik heb je nu assigned.

**Comment by Coolpower** [comment]
Ik heb iets gemaakt, waar kan ik deze afbeelding nu neerzetten?

**Comment by Coolpower** [comment]
![logo_checkjestress_2](https://cloud.githubusercontent.com/assets/16973547/12696297/0d4ae3c2-c767-11e5-9969-c6abd41f6238.png)

**Comment by Coolpower** [comment]
Ben er nog niet helemaal tevreden over

**Comment by Coolpower** [comment]
![logo_checkjestress_3](https://cloud.githubusercontent.com/assets/16973547/12696397/3bba2cd8-c76a-11e5-8f24-1a5ea45211c3.png)

**Comment by Coolpower** [comment]
Stukken beter

**Comment by Omniscimus** [comment]
:ok_hand: Zet maar in src/resources/img (nieuw mapje)

**Comment by Omniscimus** [comment]
Oh ja en vergeet de favicons niet
