### ISSUE TITLE
Favicon wordt niet weergegeven op de testwebsite

### ISSUE THREAD

**Issue by Coolpower** [MateyByrd/CheckJeStress#8]
Hoogstwaarschijnlijk heeft dit iets te maken met de locatie op de testwebsite, of de manier waarop de testwebsite gehost wordt. Na wat research ben ik er achter gekomen dat we er voor kunnen kiezen om dit favicon voor iedere pagina kunnen coden in <head> van html. Aangezien we echter niet van plan zijn om voor verschillende pagina's verschillende favicons te gebruiken, is dit volgens mij niet nodig. Iedere browser herkent namelijk ook een favicon wanneer we deze in "checkjestress.nl/" zetten. Dit is waarschijnlijk ook het probleem met de testwebsite, aangezien de favicon volgens de browser niet in de main directory staat doordat deze "indirect" gehost wordt.

**Comment by Omniscimus** [comment]
Favicon staat inderdaad in `CheckJeStress/src/favicon.ico` en niet in de website root, waardoor de browser hem niet downloadt. Ik zal het scriptje aanpassen dat de website automatisch update zodat de favicon toch in de root komt.

**Comment by Omniscimus** [comment]
~Fixed
