### ISSUE TITLE
Clickable map voor contacten in verschillende provincies

### ISSUE THREAD

**Issue by Coolpower** [MateyByrd/CheckJeStress#9]
Ik heb een site gevonden waar eenvoudig een clickable map kan worden gemaakt. Het zou kunnen zijn dat dit geld kost, maar we kunnen hier in ieder geval een goed idee vandaan halen.

http://createaclickablemap.com/create-clickable-map-netherlands.php?maplocation=netherlands

**Comment by Coolpower** [comment]
Dit zou ook nog een optie zijn, waarbij ik het helemaal zelf doe, van een zelf gekozen afbeelding:

http://dev.filkor.org/2013/04/14/create-an-interactive-map-using-javascript-and-html-5-canvas/

Is denk ik wel wat meer challenging en interessanter om te doen.

**Comment by Coolpower** [comment]
Ik heb de eerste versie van de clickable map geupload. Commentaar verwerk ik graag zelf, ga dus a.u.b. niet zelf aan dit bestand zitten prutsen

**Comment by Omniscimus** [comment]
Misschien is het een idee om de clickable map links in plaats van het verticale menu te doen, en dat hij dan mee scrollt?

**Comment by Omniscimus** [comment]
Closed by 08537132b21dc44a7c9bfa7f7159b4ea8d95ccf3

**Comment by Omniscimus** [comment]
Links werken niet
